### ISSUE TITLE
Generic Inference Algorithms: get_marginals fails with various algorithms

### ISSUE THREAD

**Issue by gankoji** [InferLO/inferlo#33]
I have the following test script, with which I'm exercising the generic inference algorithms on a small testing model:

```python
from inferlo.generic.inference.bucket_elimination import BucketElimination
from inferlo.generic.inference.inference import _convert
from inferlo import GenericGraphModel, DiscreteDomain, DiscreteFactor

# Create our generic model, all variables binary
model = GenericGraphModel(5)
for i in range(5):
    model[i].domain = DiscreteDomain.binary()

# Add our factors
factor = DiscreteFactor(model, [0], [0.05, 0.95])
model.add_factor(factor)
factor = DiscreteFactor(model, [1], [0.01, 0.99])
model.add_factor(factor)
factor = DiscreteFactor(model, [0, 1, 2], [[[0.999, 0.001], [0.9, 0.1]], [[0.95, 0.05], [0.1, 0.9]]])
model.add_factor(factor)
factor = DiscreteFactor(model, [0, 1, 3], [[[0.999, 0.001], [0.8, 0.2]], [[0.95, 0.05], [0.05, 0.95]]])
model.add_factor(factor)
factor = DiscreteFactor(model, [0, 1, 4], [[[0.999, 0.001], [0.7, 0.3]], [[0.95, 0.05], [0.025, 0.975]]])
model.add_factor(factor)

# Use BucketElimination (Variable Elimination) to marginalize the model
algo = BucketElimination(_convert(model))
BE = algo.get_marginal_factor(exception_variables=["V2", "V3", "V4"])
print(f"Probability of all nodes failing: {BE.values[0][0][0]:6.5f}")
oneNode = BE.values[0][1][1] + BE.values[1][0][1] + BE.values[1][1][0]
print(f"Probability of one node failing: {oneNode:6.5f}")

# Next, we try using the helper functions from inference.py
from inferlo.generic.inference.inference import get_marginals, mini_bucket_elimination
from inferlo.generic.inference.inference import bucket_renormalization

result = get_marginals(model, bucket_renormalization, var_ids= [2,3,4])
print(f"get_marginals result:\n {result}")
```

So far, I've only had a successful result with the `mini_bucket_elimination` and `weighted_mini_bucket_elimination` algorithms. All other choices have led to errors, which I will list here below:

`belief_propagation`
```powershell
Traceback (most recent call last):
  File "D:\PersonalWorkspace\rareEvents\GraphModels\inferLOTest.py", line 37, in <module>
    result = get_marginals(model, belief_propagation, var_ids= [2,3,4])
  File "D:\PersonalWorkspace\inferloSandbox\lib\site-packages\inferlo-0.3.1-py3.9.egg\inferlo\generic\inference\inference.py", line 262, in get_marginals
    mp[j] = log_pf_algo(restr_model)
  File "D:\PersonalWorkspace\inferloSandbox\lib\site-packages\inferlo-0.3.1-py3.9.egg\inferlo\generic\inference\inference.py", line 60, in belief_propagation
    algo.run(max_iter=max_iter,
  File "D:\PersonalWorkspace\inferloSandbox\lib\site-packages\inferlo-0.3.1-py3.9.egg\inferlo\generic\inference\belief_propagation.py", line 54, in run
    if self._is_converged(converge_thr, self.messages, old_messages):
  File "D:\PersonalWorkspace\inferloSandbox\lib\site-packages\inferlo-0.3.1-py3.9.egg\inferlo\generic\inference\belief_propagation.py", line 126, in _is_converged
    blf = product_over_(
  File "D:\PersonalWorkspace\inferloSandbox\lib\site-packages\inferlo-0.3.1-py3.9.egg\inferlo\generic\inference\factor.py", line 223, in normalize
    fac.log_values[zero_indices] = -np.inf
TypeError: 'numpy.float64' object does not support item assignment
```

`bucket_elimination`
```powershell
Traceback (most recent call last):
  File "D:\PersonalWorkspace\rareEvents\GraphModels\inferLOTest.py", line 37, in <module>
    result = get_marginals(model, bucket_elimination, var_ids= [2,3,4])
  File "D:\PersonalWorkspace\inferloSandbox\lib\site-packages\inferlo-0.3.1-py3.9.egg\inferlo\generic\inference\inference.py", line 262, in get_marginals
    mp[j] = log_pf_algo(restr_model)
  File "D:\PersonalWorkspace\inferloSandbox\lib\site-packages\inferlo-0.3.1-py3.9.egg\inferlo\generic\inference\inference.py", line 87, in bucket_elimination
    return algo.run(elimination_order_method=elimination_order_method)
  File "D:\PersonalWorkspace\inferloSandbox\lib\site-packages\inferlo-0.3.1-py3.9.egg\inferlo\generic\inference\bucket_elimination.py", line 36, in run
    eliminated_model = eliminate_variables(self.model, elimination_order)
  File "D:\PersonalWorkspace\inferloSandbox\lib\site-packages\inferlo-0.3.1-py3.9.egg\inferlo\generic\inference\bucket_elimination.py", line 16, in eliminate_variables
    model.contract_variable(var)
  File "D:\PersonalWorkspace\inferloSandbox\lib\site-packages\inferlo-0.3.1-py3.9.egg\inferlo\generic\inference\graphical_model.py", line 64, in contract_variable
    new_factor.marginalize([variable], operator=operator, **kwargs)
  File "D:\PersonalWorkspace\inferloSandbox\lib\site-packages\inferlo-0.3.1-py3.9.egg\inferlo\generic\inference\factor.py", line 160, in marginalize
    raise ValueError(
ValueError: V2 not in scope.
```

`bucket_renormalization`
```powershell
Traceback (most recent call last):
  File "D:\PersonalWorkspace\rareEvents\GraphModels\inferLOTest.py", line 37, in <module>
    result = get_marginals(model, bucket_renormalization, var_ids= [2,3,4])
  File "D:\PersonalWorkspace\inferloSandbox\lib\site-packages\inferlo-0.3.1-py3.9.egg\inferlo\generic\inference\inference.py", line 262, in get_marginals
    mp[j] = log_pf_algo(restr_model)
  File "D:\PersonalWorkspace\inferloSandbox\lib\site-packages\inferlo-0.3.1-py3.9.egg\inferlo\generic\inference\inference.py", line 112, in bucket_renormalization
    algo = BucketRenormalization(_convert(model), ibound=ibound)
  File "D:\PersonalWorkspace\inferloSandbox\lib\site-packages\inferlo-0.3.1-py3.9.egg\inferlo\generic\inference\bucket_renormalization.py", line 19, in __init__
    self._initialize_projectors()
  File "D:\PersonalWorkspace\inferloSandbox\lib\site-packages\inferlo-0.3.1-py3.9.egg\inferlo\generic\inference\bucket_renormalization.py", line 25, in _initialize_projectors
    main_rvar = self.variables_replicated_from_[var][-1]
IndexError: list index out of range
```

`iterative_join_graph_propagation`
```powershell
Traceback (most recent call last):
  File "D:\PersonalWorkspace\rareEvents\GraphModels\inferLOTest.py", line 37, in <module>
    result = get_marginals(model, iterative_join_graph_propagation, var_ids= [2,3,4])
  File "D:\PersonalWorkspace\inferloSandbox\lib\site-packages\inferlo-0.3.1-py3.9.egg\inferlo\generic\inference\inference.py", line 262, in get_marginals
    mp[j] = log_pf_algo(restr_model)
  File "D:\PersonalWorkspace\inferloSandbox\lib\site-packages\inferlo-0.3.1-py3.9.egg\inferlo\generic\inference\inference.py", line 144, in iterative_join_graph_propagation
    algo = IterativeJoinGraphPropagation(_convert(model), ibound=ibound)
  File "D:\PersonalWorkspace\inferloSandbox\lib\site-packages\inferlo-0.3.1-py3.9.egg\inferlo\generic\inference\belief_propagation.py", line 178, in __init__
    model.contract_variable(var)
  File "D:\PersonalWorkspace\inferloSandbox\lib\site-packages\inferlo-0.3.1-py3.9.egg\inferlo\generic\inference\graphical_model.py", line 64, in contract_variable
    new_factor.marginalize([variable], operator=operator, **kwargs)
  File "D:\PersonalWorkspace\inferloSandbox\lib\site-packages\inferlo-0.3.1-py3.9.egg\inferlo\generic\inference\factor.py", line 160, in marginalize
    raise ValueError(
ValueError: V2 not in scope.
```

`mean_field`
```powershell
Traceback (most recent call last):
  File "D:\PersonalWorkspace\rareEvents\GraphModels\inferLOTest.py", line 37, in <module>
    result = get_marginals(model, mean_field, var_ids= [2,3,4])
  File "D:\PersonalWorkspace\inferloSandbox\lib\site-packages\inferlo-0.3.1-py3.9.egg\inferlo\generic\inference\inference.py", line 262, in get_marginals
    mp[j] = log_pf_algo(restr_model)
  File "D:\PersonalWorkspace\inferloSandbox\lib\site-packages\inferlo-0.3.1-py3.9.egg\inferlo\generic\inference\inference.py", line 167, in mean_field
    return MeanField(_convert(model)).run()
  File "D:\PersonalWorkspace\inferloSandbox\lib\site-packages\inferlo-0.3.1-py3.9.egg\inferlo\generic\inference\mean_field.py", line 40, in __init__
    self.model.get_cardinality_for_(var))
  File "D:\PersonalWorkspace\inferloSandbox\lib\site-packages\inferlo-0.3.1-py3.9.egg\inferlo\generic\inference\graphical_model.py", line 46, in get_cardinality_for_
    factor = next(
StopIteration
```

Each is worth investigating on its own, although there is a commonality between `bucket_elimination` and `iterative_join_graph_propagation`.

**Comment by fedimser** [comment]
Hi Jake, thanks for the bug report.

1. First of all, you probably shouldn't use `get_marginals`, because this is very inefficient and inaccurate method. What it does is to find P(v_i=x) is: compute Z for original model; restrict model to model where v_i=x; compute Z for new model; compute ratio of these two Zs. 
I added this method because I was doing a research project in which I proposed more clever meta-algorithm ("Binary Tree Elimination") which computed marginal probabilities by calling other algorithms many times, and I needed something to compare it against. Results are [here](https://inferlo.github.io/inferlo/experiments/marginal_probabilities.html), `get_marginals` is called "Trivial Reduction" there and you can see from charts how bad it is.
`get_marginals` would give correct answer only when underlying algorithm (which computes Z for given model) is exact (e.g. bucket elimination), which is possible only for small models. When underlying algorithm is not exact, `get_marginals` is practically useless.

2. The common reason for all these failures is because inference algorithms were not correctly handling cases when model didn't depend at all on one of its variables. I am going to fix this by adding a dummy factor (PR #34). I added a test there based on your code, which ensures that `get_marginals` doesn't fail.

3. Some real reasons for failures that I found while debugging:
- In `belief_propagation.py`, in `get_marginal_probabilities` on line 79, we assume that all `marginals` are 1d arrays, but they may be scalars (in case when model doesn't depend on corrresponding variable);
-  In `factor.py`, in `normalize`, we need to handle case when factor is scalar separately. 
- Numpy's functions like `log` and `exp`, when given scalar `np.array` (e.g. `np.array(1.0)`), return not scalar array, as one would expect, but simply `np.float64`. This is why if we wanted correctly handle scalar factors, we would need to wrap all such functions in `np.array()`.

4. So, what should you use to get marginals instead of `get_marginals`? Try methods in `inference` package which return `InferenceResult`. These are `belief_propagation` and binary tree elimination algorithms (ending with `_bt`). In particular, `bucket_elimination_bt` is the only exact algorithm.

**Comment by fedimser** [comment]
One more thing I discovered why debugging this issue: we should change how factor refers to variables. Currenlty it has reference to model and list of indices of variables within the model. So if you want to delete a variable from model, you would need to re-map indices in all factors. This is why I had to add dummy factor for a fix, instead of removing variable.

If we get to refactoring object model, we should do this: variables are objects independent of GMs or factors; factors reference variables, but not GMs; GM is fully defined by a list of factors.

**Comment by gankoji** [comment]
RE: not using `get_marginals`, I'd already come to the same conclusion and moved on ;). Good point, though. 

RE: refactoring factors and how they refer to variables, I agree entirely. I'm running up against this issue right now on my branch coalescing the two object models, actually. I'm currently considering doing exactly this proposed refactor in order to achieve what we're after here, but I'm worried the changes would be too extensive to effectively test/review. I might have to start fresh, refactoring things in small chunks as I go.
